# https://taskfile.dev

version: '3'

vars:
  WORKDIR: { sh: pwd }

env:
  GO111MODULE: on
  CGO_ENABLED: 0

tasks:
  test:
    desc: Tests
    cmds:
      - go test -v ./...

  yaegi-test:
    desc: Tests with yaegi
    cmds:
      - yaegi test -unsafe -v .

  ip2location:
    desc: Download databases
    vars:
      SCRIPT: "{{.WORKDIR}}/.tools/ip2location-download/main.go"
      IPV4: "{{.WORKDIR}}/IP2LOCATION-LITE-DB1.BIN"
      IPV6: "{{.WORKDIR}}/IP2LOCATION-LITE-DB1.IPV6.BIN"
    cmds:
      - go run {{.SCRIPT}} https://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.BIN.ZIP {{.IPV4}}
      - go run {{.SCRIPT}} https://download.ip2location.com/lite/IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP {{.IPV6}}

  ip2location-ascode:
    desc: Update ip2location code
    vars:
      SCRIPT: "{{.WORKDIR}}/.tools/ip2location-ascode/main.go"
      IPV4: "{{.WORKDIR}}/IP2LOCATION-LITE-DB1.BIN"
      IPV6: "{{.WORKDIR}}/IP2LOCATION-LITE-DB1.IPV6.BIN"
    cmds:
      - task: ip2location
      - go run {{.SCRIPT}} {{.IPV4}} {{.IPV6}}

  vendor:
    desc: Vendor dependencies
    cmds:
      - go mod tidy
      - go mod vendor
      # Prune
      - find vendor -type f {{ .FILTER | splitList "\n" | join " " }} -delete
      # Apply patch for Yaegi `unsafe' issue
      - git apply yaegi.patch
    vars:
      FILTER: |
        ! -name 'modules.txt'
        ! -name '*.mod'
        ! -name '*.sum'
        ! -name '*.go'
        ! -name '*.s'
        ! -name '*.c'
        ! -name '*.h'
